import os
import json
import urllib.request

url = "https://api.open-meteo.com/v1/forecast?latitude=35.6895&longitude=139.6917&current=temperature_2m,wind_speed_10m"

req = urllib.request.Request(
        url,
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10;0 Win64; x64)'})

response = urllib.request.urlopen(req)

raw_data = response.read().decode('utf-8')

cleaned_data = json.loads(raw_data)

temperature = cleaned_data["current"]["temperature_2m"]
wind_speed = cleaned_data["current"]["wind_speed_10m"]

user_name = os.environ.get("USER_NAME", "Unknown_user")
environment = os.environ.get("ENVIRONMENT", "Unknown_environment")

system_meta = {
        "username": user_name,
        "sys_environment": environment
        }
try:
    with open ("weather_report.txt", "w") as file:
        file.write("---TOKYO WEATHER REPORT---\n")
        file.write(f"Generated By: {system_meta['username']}\n")
        file.write(f"Environment: {system_meta['sys_environment']}\n")
        file.write(f"Current Temperature: {temperature}°C\n")
        file.write(f"Wind Speed: {wind_speed} km/h\n")

except Exception as e:
    print(f"An error occured while writing this file: {e}")
except FileNotFoundError:
    print("Error: 'weather_report.txt' file not found!")
